name: checkov

on:
  pull_request:
  push:
    branches: [EKS]

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: run checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        soft_fail: true
        framework: terraform
